services:

  # APACHE HTTP CONTAINER
  apache:
    image: httpd:latest
    container_name: http
    ports:
      - '8080:80'
    volumes:
      - ./app/public:/usr/local/apache2/htdocs
    restart: always

  # POSTGRESQL CONTAINER
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./app/postgres:/var/lib/postgresql/data
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./app/.env
    restart: always

  # NODE.JS CONTAINER
  nodejs:
    image: node:latest
    container_name: node.js
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "npm install && npm install dotenv --save && node app.js"
    depends_on:
      - postgres
    env_file:
      - ./app/.env
    restart: always